# -*- coding: utf-8 -*-
"""Developer_Students_on_Campus_Face_Expression_Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16-zUQJjZCVlfR3ml_gh6GYfDWOAVeBmr

# 🎭 Duygu Tanıma Projesi (Face Expression Recognition)

Bu proje, derin öğrenme yöntemlerini kullanarak insan yüzlerinden duygu analizi yapmayı amaçlar.
**MobileNetV2** mimarisi üzerinde **Transfer Learning** (Transfer Öğrenme) tekniği uygulanarak geliştirilmiştir.

### 📋 Proje Akışı:
1.  **Veri Seti Hazırlığı:** Kaggle üzerinden yüz ifadeleri veri seti indirilir.
2.  **Veri Dengeleme (Balancing):** Modelin tarafsız öğrenmesi için `angry`, `happy` ve `neutral` sınıfları eşit sayıya getirilir.
3.  **Önişleme:** Resimler 160x160 boyutuna getirilir ve normalize edilir.
4.  **Model Eğitimi:** Önce dondurulmuş katmanlarla hızlı eğitim, ardından hassas katmanlarla **Fine-Tuning** yapılır.

---

# 🛠️ 1. Hazırlık ve Kütüphanelerin Yüklenmesi
Bu bölümde gerekli Python kütüphanelerini içe aktarıyoruz ve Kaggle veri setini indirmek için gerekli yapılandırmayı hazırlıyoruz.
"""

import os
import shutil
import random
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

os.environ['KAGGLE_CONFIG_DIR'] = "/content"

# Veri setini indir ve zipten çıkar
if not os.path.exists('face-expression-recognition-dataset.zip'):
    print(" Veri seti indiriliyor...")
    !kaggle datasets download -d jonathanoheix/face-expression-recognition-dataset
    !unzip -q face-expression-recognition-dataset.zip -d .
    print("✅ İndirme ve çıkarma tamamlandı.")

"""# ⚖️ 2. Veri Setini Filtreleme ve Dengeleme (Balancing)
Modelin belirli bir duyguya (örneğin sadece 'happy') odaklanıp diğerlerini öğrenmemesini önlemek için sınıfları eşitliyoruz. Sadece `angry`, `happy` ve `neutral` sınıflarını kullanacağız.
"""

source_path = 'images/train/'
target_path = 'balanced_images/'
class_names = ['angry', 'happy', 'neutral']

# Her sınıftaki mevcut resim sayılarını bul
counts = {cls: len(os.listdir(os.path.join(source_path, cls))) for cls in class_names}
min_count = min(counts.values()) # En az veriye sahip sınıfın sayısını baz al

print(f" Mevcut veri sayıları: {counts}")
print(f" Dengeleme: Her sınıftan rastgele {min_count} adet resim seçiliyor...")

# Hedef klasörü temizle ve yeniden oluştur
if os.path.exists(target_path):
    shutil.rmtree(target_path)
os.makedirs(target_path)

for cls in class_names:
    os.makedirs(os.path.join(target_path, cls))
    all_imgs = os.listdir(os.path.join(source_path, cls))
    # Rastgele seçim yaparak sınıflar arası adaleti sağla
    selected_imgs = random.sample(all_imgs, min_count)

    for img in selected_imgs:
        shutil.copy(os.path.join(source_path, cls, img),
                    os.path.join(target_path, cls, img))

print(f"✅ Veri seti {target_path} klasöründe başarıyla dengelendi!")

"""# 📂 3. Veri Yükleme ve Önişleme
Resimleri 160x160 boyutuna getiriyoruz ve veriyi %80 Eğitim (Train), %20 Doğrulama (Validation) olarak ayırıyoruz.
"""

IMG_SIZE = (160, 160)
BATCH_SIZE = 32

# Eğitim veri seti
train_ds = tf.keras.utils.image_dataset_from_directory(
    target_path,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_names=class_names)

# Doğrulama veri seti
val_ds = tf.keras.utils.image_dataset_from_directory(
    target_path,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_names=class_names)

print("✅ Veri yükleyiciler hazır.")

"""# 🧠 4. Model Mimarisinin Oluşturulması
Bu aşamada **MobileNetV2** modelini kullanıyoruz. Önce hazır ağırlıkları dondurup (frozen) sadece kendi eklediğimiz katmanları eğiteceğiz.
"""

# MobileNetV2 için özel normalizasyon fonksiyonu
preprocess_input = tf.keras.applications.mobilenet_v2.preprocess_input

# Ana model: MobileNetV2 (Önceden eğitilmiş ağırlıklarla)
base_model = tf.keras.applications.MobileNetV2(input_shape=(160, 160, 3),
                                               include_top=False,
                                               weights='imagenet')

# Ana modeli dondur (Ağırlıklar değişmesin)
base_model.trainable = False

# Kendi mimarimizi oluşturuyoruz
model = models.Sequential([
    layers.Input(shape=(160, 160, 3)),
    layers.Lambda(preprocess_input),
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.5),
    layers.Dense(len(class_names), activation='softmax')
])

# Modeli derle
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

"""# 🚀 5. Eğitim ve Fine-Tuning
Önce sadece yeni katmanları eğitiyoruz, ardından ana modelin son katmanlarını da açarak (unfreeze) hassas bir eğitim yapıyoruz.
"""

# 1. Aşama: Sadece yeni eklenen katmanların eğitimi
print(" Adım 1: Üst katmanlar eğitiliyor (Head Training)...")
history = model.fit(train_ds, validation_data=val_ds, epochs=15)

# 2. Aşama: İnce Ayar (Fine-Tuning)
print("\n Adım 2: Fine-tuning başlatılıyor...")
base_model.trainable = True

# Son 30 katman hariç her şeyi dondur
for layer in base_model.layers[:-30]:
    layer.trainable = False


model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.00001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Eğitime devam et
fine_tune_epochs = 15
total_epochs = 15 + fine_tune_epochs
model.fit(train_ds, validation_data=val_ds, epochs=total_epochs, initial_epoch=history.epoch[-1])

print("✅ Model eğitimi başarıyla tamamlandı!")

"""# 📸 6. Canlı Tahmin (Kamera ile Test)
Bu bölümde Google Colab üzerinden kameranızı açarak bir fotoğraf çekebilir ve modelin anlık olarak duygu durumunuzu (Angry, Happy, Neutral) tahmin etmesini sağlayabilirsiniz.

> **Not:** Tarayıcınızın kamera erişimine izin vermeyi unutmayın. Fotoğraf çekimi 3 saniyelik bir gecikmeden sonra otomatik gerçekleşir.
"""

# --- BÖLÜM 6: Tahmin (Kamera) ---
def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});
      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();
      await new Promise((resolve) => setTimeout(resolve, 3000));
      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getTracks().forEach(track => track.stop());
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

try:
    print("🎬 Kamera başlatılıyor...")
    photo_file = take_photo()
    img = tf.keras.utils.load_img(photo_file, target_size=(160, 160))
    img_array = tf.keras.utils.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)

    predictions = model.predict(img_array, verbose=0)
    score = predictions[0]
    predicted_class = class_names[np.argmax(score)]
    confidence = 100 * np.max(score)

    print(f"\n TAHMİN: {predicted_class.upper()} (%{confidence:.2f})")

    plt.imshow(img)
    plt.axis('off')
    plt.title(f"{predicted_class} (%{confidence:.2f})")
    plt.show()

except Exception as e:
    print(f"⚠️ Hata: {e}")